OrdererOrgs:
  - Name: Orderer
    Domain: dvss-ppa.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.dvss-ppa.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.dvss-ppa.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
