global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'python-backend'
    static_configs:
      - targets: ['backend-python:8000']
  - job_name: 'go-backend'
    static_configs:
      - targets: ['backend-go:8001']
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
