# Hyperledger Fabric Blockchain Explorer
# 基于 https://github.com/hyperledger-labs/blockchain-explorer
version: '3.8'

services:
  # PostgreSQL数据库 - Blockchain Explorer需要
  explorer-db:
    image: postgres:13
    container_name: dvss-explorer-db
    environment:
      - POSTGRES_DB=fabricexplorer
      - POSTGRES_USER=hppoc
      - POSTGRES_PASSWORD=password
    volumes:
      - explorer_db_data:/var/lib/postgresql/data
    networks:
      - dvss-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hppoc -d fabricexplorer"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Blockchain Explorer Web应用
  blockchain-explorer:
    image: hyperledger/explorer:latest
    container_name: dvss-blockchain-explorer
    environment:
      - DATABASE_HOST=explorer-db
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config:/opt/explorer/app/platform/fabric/config
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - "8080:8080"
    networks:
      - dvss-network
    depends_on:
      explorer-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  explorer_db_data:
  walletstore:

networks:
  dvss-network:
    external: true
